version = 0.1
[default.deploy.parameters]
stack_name = "ibaraki-sam-sample-api"
resolve_s3 = true
s3_prefix = "ibaraki-sam-sample-api"
region = "ap-northeast-1"
profile = "sandbox"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
