AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: A simple hello world API using API Gateway and Lambda

Resources:
  IbarakiSamSampleApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      EndpointConfiguration:
        Type: REGIONAL

  IbarakiSamSampleFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ibaraki-sample-lambda/
      Handler: index.handler
      Runtime: nodejs18.x
      Architectures:
        - arm64
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get
            RestApiId:
              Ref: IbarakiSamSampleApi
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "ES2020"
        Sourcemap: true
        EntryPoints:
          - src/index.ts
